export const inventory = [
  {
    id: "byd-atto-3",
    name: "BYD Atto 3",
    year: "2024",
    fuel: "Electric",
    type: "Brand New",
    mileage: "0 km",
    price: 6800000,
    brand: "BYD",
    body: "Crossover",
    availability: "Available",
    image: "/cat-crossover.webp",
    isEv: true,
  },
  {
    id: "toyota-prado-pre-order",
    name: "Toyota Land Cruiser Prado",
    year: "2025",
    fuel: "Octane",
    type: "Pre Order",
    mileage: "Factory Order",
    price: 14500000,
    brand: "Toyota",
    body: "SUV",
    availability: "Pre Order",
    image: "/cat-suv.webp",
  },
  {
    id: "land-cruiser-lc300",
    name: "Land Cruiser LC300 ZX",
    year: "2022",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "23K km",
    price: 37900000,
    brand: "Toyota",
    body: "SUV",
    availability: "Available",
    image: "/stock-noah-2023.webp",
  },
  {
    id: "bmw-x7-blue",
    name: "BMW X7",
    year: "2021",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "15K km",
    price: 27900000,
    brand: "BMW",
    body: "SUV",
    availability: "Available",
    image: "/cat-mpv.webp",
  },
  {
    id: "bmw-x7-black",
    name: "BMW X7 Xdrive40i M-Sport",
    year: "2022",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "15K km",
    price: 26900000,
    brand: "BMW",
    body: "SUV",
    availability: "Available",
    image: "/cat-crossover.webp",
  },
  {
    id: "range-rover-2020",
    name: "Range Rover Vogue Autobiography",
    year: "2020",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "5K Miles",
    price: 24900000,
    brand: "Land Rover",
    body: "SUV",
    availability: "Available",
    image: "/cat-wagon.webp",
  },
  {
    id: "range-rover-2019",
    name: "Range Rover Vogue Autobiography",
    year: "2019",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "14K km",
    price: 21900000,
    brand: "Land Rover",
    body: "SUV",
    availability: "Available",
    image: "/stock-axio.webp",
  },
  {
    id: "mercedes-s560e",
    name: "Mercedes-Benz S 560e",
    year: "2019",
    fuel: "Octane (H)",
    type: "Pre Owned",
    mileage: "11K m",
    price: 18900000,
    brand: "Mercedes-Benz",
    body: "Sedan",
    availability: "Available",
    image: "/stock-noah-black.webp",
  },
  {
    id: "land-cruiser-zx-v8",
    name: "Land Cruiser Zx-V8",
    year: "2015",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "71K km",
    price: 18900000,
    brand: "Toyota",
    body: "SUV",
    availability: "Available",
    image: "/stock-noah-white.webp",
  },
  {
    id: "bmw-745le",
    name: "BMW 745Le",
    year: "2019",
    fuel: "Octane",
    type: "Pre Owned",
    mileage: "15K km",
    price: 18900000,
    brand: "BMW",
    body: "Sedan",
    availability: "Available",
    image: "/stock-noah-pearl.webp",
  },
  {
    id: "toyota-alphard",
    name: "Toyota Alphard",
    year: "2024",
    fuel: "Octane (H)",
    type: "Reconditioned",
    mileage: "8K km",
    price: 16900000,
    brand: "Toyota",
    body: "MPV",
    availability: "Available",
    image: "/stock-noah-2023.webp",
  },
  {
    id: "land-cruiser-vx-2016",
    name: "Land Cruiser Vx-V8",
    year: "2016",
    fuel: "Diesel",
    type: "Pre Owned",
    mileage: "41K km",
    price: 16900000,
    brand: "Toyota",
    body: "SUV",
    availability: "Available",
    image: "/cat-suv.webp",
  },
  {
    id: "land-cruiser-vx-2015",
    name: "Land Cruiser Vx-V8",
    year: "2015",
    fuel: "Diesel",
    type: "Pre Owned",
    mileage: "74K km",
    price: 15900000,
    brand: "Toyota",
    body: "SUV",
    availability: "Available",
    image: "/cat-crossover.webp",
  },
  {
    id: "lexus-rx500h",
    name: "Lexus RX 500h Turbo",
    year: "2023",
    fuel: "Octane (H)",
    type: "Pre Owned",
    mileage: "22K km",
    price: 14900000,
    brand: "Lexus",
    body: "Crossover",
    availability: "Available",
    image: "/stock-axio.webp",
  },
];

export function formatPrice(price: number) {
  return `BDT ${new Intl.NumberFormat("en-IN").format(price)}`;
}
